### ISSUE TITLE
Is it possible to make it bidirectional

### ISSUE THREAD

**Issue by ThorsenRune** [G6EJD/ESP32-Webserver-with-UDP#1]
Fantastic project, thanks for sharing
It seems like this only writes to the devices. Can it be setup to read data from the devices as well. Id like to read some 1ksps ADC values ?

**Comment by G6EJD** [comment]
It’s not an issue it’s a feature request😀
I’m not sure I understand what your trying to do, you can send UDP data byte by byte so you just need to read the ADC then send the data via UDP in the loop.

**Comment by G6EJD** [comment]
udp.printf("C01H");

In your case read ADC int reading = readADC then UDP.print(reading) in simple terms.

**Comment by ThorsenRune** [comment]
> It’s not an issue it’s a feature request😀
> I’m not sure I understand what your trying to do, you can send UDP data byte by byte so you just need to read the ADC then send the data via UDP in the loop.

Thnks. Yes Its a request but I could only file it under issues. Sorry.

**Comment by G6EJD** [comment]
I think you’ll find that sending readings via UDP is actually quite easy did you mean sending it from a client ESP32? If so just read the port and send the data

**Comment by G6EJD** [comment]
Maybe put some text around it like ‘device-1,1234’ so you know where it came from

**Comment by ThorsenRune** [comment]
Just ran the code and it seems to work nicely. However I was looking for the best way to transfer (transceive bidirectionally) data (1ksps) from ESP32/ESP8266 to the browser. I guess that is not possible as the browser will not be able to make a UDP connection. Right?
Any ideas? I see you have lots of nice projects and maybe one will do?

**Comment by G6EJD** [comment]
I’ve been experimenting with sending data via xtml to a browser as you describe, but the best rate I can get is a few characters per second. You can stream data to a browser window but it won’t go at that rate, well it will if you copy the data to a file then stream that to a browser, I’ve provided code to do that with the sensor server. Not real time but near real time.
